### ISSUE TITLE
Communication with ES

### ISSUE THREAD

**Issue by thomasjohansen** [search-node/search_node#2]
I'm not sure how and when. But getting this error:
messages.log - ERROR Search error: No Living connections

Nginx says Bad gateway when requesting.

app.js is running.

Only way to getting it to work again is with "sudo service supervisor restart"

**Comment by cableman** [comment]
Are there any hints in /var/log/elasticsearch/*.log

**Comment by thomasjohansen** [comment]
[action.index             ] [Wrath] [df4f7ab089713e1e264c6ea6fb2b358e][4], node[IECz-0JDTjSP_rfoOBY6rA], [P], s[STARTED]: Failed to execute [index {[df4f7ab089713e1e264c6ea6fb2b358e][store][89], source[{"search_api_language":"en","status":"1","title":"Inspiration Buus","type":"store","url":"http:\/\/luciekaas.com.dev.zhosting.dk\/content\/inspiration-buus"}]}]
org.elasticsearch.index.mapper.MapperParsingException: Wrong value for index [analysed] for field [title]
       	at org.elasticsearch.index.mapper.core.TypeParsers.parseIndex(TypeParsers.java:356)
       	at org.elasticsearch.index.mapper.core.TypeParsers.parseField(TypeParsers.java:174)
       	at org.elasticsearch.index.mapper.core.StringFieldMapper$TypeParser.parse(StringFieldMapper.java:153)
       	at org.elasticsearch.index.mapper.object.RootObjectMapper.findTemplateBuilder(RootObjectMapper.java:236)
       	at org.elasticsearch.index.mapper.object.RootObjectMapper.findTemplateBuilder(RootObjectMapper.java:222)
       	at org.elasticsearch.index.mapper.object.ObjectMapper.parseDynamicValue(ObjectMapper.java:792)
       	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:708)
       	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
       	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
       	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
       	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:492)
       	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:192)
       	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
       	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
       	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       	at java.lang.Thread.run(Thread.java:745)

**Comment by cableman** [comment]
Just add better logger in development branch: https://github.com/search-node/search_node/commit/48e908ad98f787eb5bfddef65df84fe856a64efb

But not sure that will give anything, as I understand it its because there is not connection to ES.

**Comment by thomasjohansen** [comment]
Upgrading node seems to be working.
